// <auto-generated />
using ConfigStore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ConfigStore.Api.Migrations
{
    [DbContext(typeof(ConfigStoreContext))]
    [Migration("20180104115718_Cascade delete Envs on App delete")]
    partial class CascadedeleteEnvsonAppdelete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfigStore.Api.Data.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Key");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("ConfigStore.Api.Data.ServiceEnvironment", b =>
                {
                    b.Property<int>("ApplicationId");

                    b.Property<string>("Name");

                    b.HasKey("ApplicationId", "Name");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("ConfigStore.Api.Data.ServiceEnvironment", b =>
                {
                    b.HasOne("ConfigStore.Api.Data.Application", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
